site_name: x-inker`s notes
copyright: Copyright &copy; 2016 - 2023 x-inker
repo_url: https://github.com/Italink/ModernGraphicsEngineGuide
repo_name: Github
nav:
theme:
    icon:
        repo: fontawesome/brands/github
    language: zh
    name: material
    custom_dir: docs/stylesheet
    features:
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
plugins:
    - search:
        separator: '[\s\u200b\-]'
    - git-revision-date-localized:
        enable_creation_date: true
        type: iso_datetime
markdown_extensions:
    - abbr
    - admonition
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
extra_css:
  - stylesheet/mkdocs_extra.css

extra_javascript:
  - stylesheet/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
